// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obzhccxrivnrcclsssnh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9iemhjY3hyaXZucmNjbHNzc25oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEyMDY5MjksImV4cCI6MjA2Njc4MjkyOX0.kD6swpZx0rNnRsV45sWa1fI1xVZEtiVsSsqcBoo8qS8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});